drone_config:
  dimensions_cm: 30      # sphere diameter the drone can pass through
  max_rotate_deg: 90     # max rotation per command
  max_advance_cm: 15     # max advance distance per command
  max_elevate_cm: 10     # max elevate distance per command

  # Lidar sensor parameters
  lidar_zmin_cm: 20
  lidar_zmax_cm: 150
  lidar_d: 2.5
  lidar_fovc: 5
